[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@layerzero/=lib/solidity-examples/contracts/',
    '@chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/',
    'chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/contracts/src/v0.8/',
    'solmate/=lib/solmate/src/'
]


fs_permissions = [
    {access = "write", path = "./deployments/"},
    {access = "read", path = "./src/scripts/"}
]


solc_version = "0.8.17"
optimizer = true
optimizer_runs = 10
# See more config options https://github.com/foundry-rs/foundry/tree/master/config


[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }